// Code generated by protoc-gen-twirpts. DO NOT EDIT.

let host: string = "";

// setHost is useful if the API you're calling is not on the same host as your web server
export function setHost(newHost: string) {
	host = newHost;
}

export enum TwirpErrorCode {
	NoError = "NoError",
	Canceled = "Canceled",
	Unknown = "Unknown",
	Invalid_Argument = "Invalid_Argument",
	Malformed = "Malformed",
	Deadline_Exceeded = "Deadline_Exceeded",
	Not_Found = "Not_Found",
	Bad_Route = "Bad_Route",
	Already_Exists = "Already_Exists",
	Permission_Denied = "Permission_Denied",
	Unauthenticated = "Unauthenticated",
	Resource_Exhausted = "Resource_Exhausted",
	Failed_Precondition = "Failed_Precondition",
	Aborted = "Aborted",
	Out_Of_Range = "Out_Of_Range",
	Unimplemented = "Unimplemented",
	Internal = "Internal",
	Unavailable = "Unavailable",
	Data_Loss = "Data_Loss",
}

export class TwirpError extends Error {
	constructor(
		public code: TwirpErrorCode,
		public message: string,
		public meta?: any,
	) {
		super(code + ": " + message);
	}
}

// Patch BigInt support into JSON.stringify
BigInt.prototype["toJSON"] = function () { return this.toString() }

// Use a custom parser to allow for bigints to be properly created
async function parseJSON(res: Response): Promise<any> {
	const text = await res.text();
	return JSON.parse(text, (key, value) => {
		// For anything more than 15 digits, assume it's a bigint.
		// There is an edge case where a number with 15 digits or more will be treated as a bigint.
		if (typeof value === "string" && value.match(/^\d{15,}$/)) {
			return BigInt(value);
		}
		return value;
	});
}

function createRequest(url: string, body: any): Request {
	return new Request(host + url, {
		method: "POST",
		credentials: "same-origin",
		headers: {
			"Content-Type": "application/json",
		},
		body: JSON.stringify(body),
	});
}

// This is a multi-line comment using double slashes
// and should render appropriately on output.
export async function getAccountDetails(args: { accountEmail?: string }): Promise<{ account?: { accountId?: bigint, email?: string, coinCount?: bigint } }> {
	const res = await fetch(createRequest("/rpc/account.Accounts/GetAccountDetails", args));
	const jsonBody = await parseJSON(res);
	if (res.ok) {
		return jsonBody;
	}
	throw new TwirpError(jsonBody.code, jsonBody.msg, jsonBody.meta);
}

// This is a multi-line block comment, which is
//also expected to render properly.
export async function logout(args: { accountId?: bigint, token?: string }): Promise<{  }> {
	const res = await fetch(createRequest("/rpc/account.Accounts/Logout", args));
	const jsonBody = await parseJSON(res);
	if (res.ok) {
		return jsonBody;
	}
	throw new TwirpError(jsonBody.code, jsonBody.msg, jsonBody.meta);
}

export async function noComment(args: { accountId?: bigint, token?: string }): Promise<{  }> {
	const res = await fetch(createRequest("/rpc/account.Accounts/NoComment", args));
	const jsonBody = await parseJSON(res);
	if (res.ok) {
		return jsonBody;
	}
	throw new TwirpError(jsonBody.code, jsonBody.msg, jsonBody.meta);
}

// Creates a checkout session for the given item.
export async function createCheckoutSession(args: { itemId?: string }): Promise<{ sessionId?: string }> {
	const res = await fetch(createRequest("/rpc/shop.Shop/CreateCheckoutSession", args));
	const jsonBody = await parseJSON(res);
	if (res.ok) {
		return jsonBody;
	}
	throw new TwirpError(jsonBody.code, jsonBody.msg, jsonBody.meta);
}

