// <auto-generated>
//     Generated by protoc-gen-twirpcs.  DO NOT EDIT!
// </auto-generated>
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Google.Protobuf; // For ".ToByteArray()"

public class GeneratedAPI {
  public static readonly MediaTypeWithQualityHeaderValue CONTENT_TYPE_PROTOBUF = new MediaTypeWithQualityHeaderValue("application/protobuf");

  private delegate Resp doParsing<Resp>(byte[] data) where Resp : IMessage;
  private static async Task<Resp> DoRequest<Req, Resp>(HttpClient client, string address, Req req, doParsing<Resp> parserFunc) where Req : IMessage where Resp : IMessage {
    using (var content = new ByteArrayContent(req.ToByteArray())) {
      content.Headers.ContentType = CONTENT_TYPE_PROTOBUF;
      using (HttpResponseMessage response = await client.PostAsync(address, content)) {
        response.EnsureSuccessStatusCode();
        var byteArr = await response.Content.ReadAsByteArrayAsync();
        return parserFunc(byteArr);
      }
    }
  }

  // This is a multi-line comment using double slashes
  // and should render appropriately on output.
  public static async Task<Accounts.AccountDetailsResponse> GetAccountDetails(HttpClient client, Accounts.AccountDetailsRequest req) {
    return await DoRequest<Accounts.AccountDetailsRequest, Accounts.AccountDetailsResponse>(client, "/rpc/account.Accounts/GetAccountDetails", req, Accounts.AccountDetailsResponse.Parser.ParseFrom);
  }

  // This is a multi-line block comment, which is
  //also expected to render properly.
  public static async Task<Accounts.LogoutResponse> Logout(HttpClient client, Accounts.LogoutRequest req) {
    return await DoRequest<Accounts.LogoutRequest, Accounts.LogoutResponse>(client, "/rpc/account.Accounts/Logout", req, Accounts.LogoutResponse.Parser.ParseFrom);
  }

  public static async Task<Accounts.LogoutResponse> NoComment(HttpClient client, Accounts.LogoutRequest req) {
    return await DoRequest<Accounts.LogoutRequest, Accounts.LogoutResponse>(client, "/rpc/account.Accounts/NoComment", req, Accounts.LogoutResponse.Parser.ParseFrom);
  }

  // Creates a checkout session for the given item.
  public static async Task<Shop.CheckoutResponse> CreateCheckoutSession(HttpClient client, Shop.CheckoutRequest req) {
    return await DoRequest<Shop.CheckoutRequest, Shop.CheckoutResponse>(client, "/rpc/shop.Shop/CreateCheckoutSession", req, Shop.CheckoutResponse.Parser.ParseFrom);
  }
}
